### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by vedantpuri** [mayankk2308/nutshell#22]
Propose a new logo for this repo !

@ggabogarcia you could post your suggestions here :)

**Comment by ggabogarcia** [comment]
Hello sir!, thanks a lot, I'll start sketching :)

**Comment by SachithMayantha** [comment]
What's

**Comment by SachithMayantha** [comment]
![mylogo 2](https://user-images.githubusercontent.com/38182512/43674423-7ddcadac-97f1-11e8-94e1-64394cdd2b0f.jpg)

**Comment by ggabogarcia** [comment]
Hello sir, sorry for the delay, the truth was not easy for me to generate an idea, I relied a bit on what he said, but I used another range of colors with more contrast. The main idea is "voice waves".

![universal](https://user-images.githubusercontent.com/35750428/43819811-e52ffef4-9aa9-11e8-8ae0-811a0ed5a995.png)

**Comment by vedantpuri** [comment]
Thanks for your suggestion. However I feel these are not the best for a macOS app icon. Do let me know if you have any other suggestions later on 👍

**Comment by ggabogarcia** [comment]
Hello, here are my last two proposal sir. I hope you like them.
![universale](https://user-images.githubusercontent.com/35750428/43865058-09310eba-9b27-11e8-86bf-3ee73c8ad97f.png)

**Comment by ggabogarcia** [comment]
Hello, I would like to know your opinion about the latest designs I sent.

**Comment by mayankk2308** [comment]
@ggabogarcia Like the icons, primarily the first one. Shape is more iOS-like than macOS; the latter is more flexible with respect to app icons. Some examples to consider: Atom's icon, Affinity Designer/Photo icons, etc - have non-standard yet great shape. What are your thoughts on somehow combining the first and second concept (waves + terminal) packaged into a somewhat unique shape?

**Comment by mayankk2308** [comment]
Decided.
