### ISSUE TITLE
No check if file with same destination name already exists for 'rename'

### ISSUE THREAD

**Issue by vedantpuri** [mayankk2308/nutshell#7]
This check needs to be added to the _requestHandler_ function.

**Comment by vedantpuri** [comment]
@mayankk2308 could throw a popup like we get in mac, as to keep both, replace or cancel. Just an idea for later use.

**Comment by mayankk2308** [comment]
The rename (`mv`) command will return a message about this on `stderr`. We can add this as an enhancement later.
